question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
      "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
      "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
      "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
      "question": "&quot;Windows NT&quot; is a monolithic kernel.", "correct_answer": "False",
      "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                       "question": "The open source program Redis is a relational database server.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
      "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
      "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
      "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
      "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "hard", "category": "Science: Computers",
                                       "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
      "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
      "correct_answer": "False", "incorrect_answers": ["True"]}]
